/**
 * Official MEIL (Megha Engineering & Infrastructures Ltd.) Portfolio Data
 * Core Business Units and Projects / Sites hierarchy.
 * Source: Official MEIL Portfolios (Transportation, Buildings, Hydrocarbons,
 * Renewable Energy, Power, Drinking Water, Irrigation, International Business Development).
 */

export interface MeilProject {
  id: string
  code: string
  name: string
  buId: string
  buName: string
  location: string
  stateOrCountry: string
  category: string
  status: 'ACTIVE' | 'IN_OPERATION' | 'COMMISSIONING' | 'EXPANSION'
  esgScore: number
  brsrCore: boolean
  reportingOwner: string
  description: string
}

export interface MeilBusinessUnit {
  id: string
  code: string
  name: string
  shortName: string
  subsidiaryCode: string
  subsidiaryName: string
  sector: string
  iconName: string
  accentColor: string
  gradient: string
  description: string
  projects: MeilProject[]
}

export const MEIL_ORGANIZATIONS = [
  { id: 'MEIL-GROUP', code: 'MEIL', name: 'MEIL Group', legalName: 'Megha Engineering & Infrastructures Ltd.', cin: 'U45200TG2006PLC050278' },
  { id: 'MEIL-POWER', code: 'MEIL-PWR', name: 'MEIL Power Systems', legalName: 'MEIL Power Systems Ltd.', cin: 'U40300MH2010PLC123456' },
  { id: 'MEIL-INFRA', code: 'MEIL-INFRA', name: 'MEIL Infrastructure', legalName: 'MEIL Infra Ventures Ltd.', cin: 'U70102MH2011PLC654321' },
  { id: 'MEIL-HYDRO', code: 'MEIL-HC', name: 'MEIL Hydrocarbons & Energy', legalName: 'MEIL Hydrocarbons Ltd.', cin: 'U23200DL2012PLC987654' },
]

export const MEIL_BUSINESS_UNITS: MeilBusinessUnit[] = [
  {
    id: 'bu-transportation',
    code: 'MEIL-TRANS',
    name: 'Transportation',
    shortName: 'Transport',
    subsidiaryCode: 'MEIL-INFRA',
    subsidiaryName: 'MEIL Infrastructure',
    sector: 'Highways, Expressways & Tunnels',
    iconName: 'Route',
    accentColor: '#0284C7',
    gradient: 'from-sky-500 to-blue-600',
    description: 'National expressways, high-altitude strategic tunnels, and economic transport corridors.',
    projects: [
      {
        id: 'trans-01',
        code: 'MEIL-TR-ZOJ',
        name: 'Zojila Tunnel',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Jammu & Kashmir',
        stateOrCountry: 'Jammu & Kashmir',
        category: 'Strategic High-Altitude Tunnel',
        status: 'ACTIVE',
        esgScore: 89,
        brsrCore: true,
        reportingOwner: 'Er. R. Sharma',
        description: 'Asia’s longest bi-directional road tunnel connecting Srinagar with Leh across the Zojila Pass.',
      },
      {
        id: 'trans-02',
        code: 'MEIL-TR-DAK',
        name: 'Delhi–Amritsar–Katra Expressway',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Punjab / J&K',
        stateOrCountry: 'Punjab / J&K',
        category: 'Access-Controlled Expressway',
        status: 'ACTIVE',
        esgScore: 92,
        brsrCore: true,
        reportingOwner: 'Er. A. Kaul',
        description: 'Greenfield economic expressway corridor connecting Delhi with pilgrimage and economic hubs.',
      },
      {
        id: 'trans-03',
        code: 'MEIL-TR-MSM',
        name: 'Maharashtra Samruddhi Mahamarg',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Maharashtra',
        stateOrCountry: 'Maharashtra',
        category: 'Super Communication Expressway',
        status: 'IN_OPERATION',
        esgScore: 94,
        brsrCore: true,
        reportingOwner: 'Er. V. Deshmukh',
        description: 'Nagpur–Mumbai 701-km flagship high-speed corridor with green plantations and wildlife passes.',
      },
      {
        id: 'trans-04',
        code: 'MEIL-TR-ADB',
        name: 'Amas–Darbhanga Expressway',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Bihar',
        stateOrCountry: 'Bihar',
        category: 'Economic Corridor Expressway',
        status: 'ACTIVE',
        esgScore: 87,
        brsrCore: true,
        reportingOwner: 'Er. S. Mishra',
        description: 'North-South arterial high-speed corridor connecting southern and northern Bihar.',
      },
      {
        id: 'trans-05',
        code: 'MEIL-TR-RNP',
        name: 'Renigunta–Naidupeta Road Project',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Andhra Pradesh',
        stateOrCountry: 'Andhra Pradesh',
        category: 'Four-Lane Highway',
        status: 'IN_OPERATION',
        esgScore: 90,
        brsrCore: true,
        reportingOwner: 'Er. K. Reddy',
        description: 'Strategic highway link connecting industrial corridors and port logistics nodes.',
      },
      {
        id: 'trans-06',
        code: 'MEIL-TR-VWB',
        name: 'Vijayawada Western Bypass',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Andhra Pradesh',
        stateOrCountry: 'Andhra Pradesh',
        category: 'Urban Bypass Expressway',
        status: 'ACTIVE',
        esgScore: 88,
        brsrCore: true,
        reportingOwner: 'Er. P. Rao',
        description: 'Multi-lane heavy freight bypass alleviating urban traffic bottlenecks.',
      },
      {
        id: 'trans-07',
        code: 'MEIL-TR-BVE',
        name: 'Bengaluru–Vijayawada Economic Corridor',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Karnataka / Andhra Pradesh',
        stateOrCountry: 'Karnataka / AP',
        category: 'Inter-State Economic Corridor',
        status: 'ACTIVE',
        esgScore: 91,
        brsrCore: true,
        reportingOwner: 'Er. M. Hegde',
        description: 'Bharatmala Pariyojana high-speed freight link between southern tech and industrial hubs.',
      },
      {
        id: 'trans-08',
        code: 'MEIL-TR-NVE',
        name: 'Nagpur–Vijayawada Economic Corridor',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Maharashtra / AP',
        stateOrCountry: 'Maharashtra / AP',
        category: 'Freight Economic Corridor',
        status: 'ACTIVE',
        esgScore: 89,
        brsrCore: true,
        reportingOwner: 'Er. G. Patil',
        description: 'Multi-state logistics expressway streamlining central to eastern India cargo flow.',
      },
      {
        id: 'trans-09',
        code: 'MEIL-TR-SCE',
        name: 'Surat–Chennai Economic Corridor',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Gujarat / Tamil Nadu',
        stateOrCountry: 'Gujarat / TN',
        category: 'Trans-India Economic Corridor',
        status: 'ACTIVE',
        esgScore: 93,
        brsrCore: true,
        reportingOwner: 'Er. D. Shah',
        description: 'Greenfield trans-peninsular arterial logistics corridor connecting western and southern ports.',
      },
      {
        id: 'trans-10',
        code: 'MEIL-TR-TNB',
        name: 'Tejaji Nagar–Balwara Road Project',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Madhya Pradesh',
        stateOrCountry: 'Madhya Pradesh',
        category: 'State Highway Upgrade',
        status: 'IN_OPERATION',
        esgScore: 86,
        brsrCore: true,
        reportingOwner: 'Er. R. Chouhan',
        description: 'Vital regional connectivity upgrade promoting rural-urban economic exchange.',
      },
      {
        id: 'trans-11',
        code: 'MEIL-TR-SMR',
        name: 'Siwan–Mashrak Road Project',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Bihar',
        stateOrCountry: 'Bihar',
        category: 'Inter-District Highway',
        status: 'IN_OPERATION',
        esgScore: 85,
        brsrCore: true,
        reportingOwner: 'Er. B. Singh',
        description: 'Key roadway infrastructure modernizing vehicular connectivity in northern Bihar.',
      },
      {
        id: 'trans-12',
        code: 'MEIL-TR-NH66',
        name: 'NH-66 Highway Works',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Kerala',
        stateOrCountry: 'Kerala',
        category: 'Coastal Highway Modernization',
        status: 'ACTIVE',
        esgScore: 90,
        brsrCore: true,
        reportingOwner: 'Er. T. Nair',
        description: 'Expansion and modern multi-lane restructuring of the scenic Arabian Sea coastal route.',
      },
      {
        id: 'trans-13',
        code: 'MEIL-TR-AMJ',
        name: 'Appa–Manneguda Junction Improvement',
        buId: 'bu-transportation',
        buName: 'Transportation',
        location: 'Telangana',
        stateOrCountry: 'Telangana',
        category: 'Junction Grade Separator',
        status: 'ACTIVE',
        esgScore: 88,
        brsrCore: true,
        reportingOwner: 'Er. C. Prasad',
        description: 'Flyover grade-separation and safety junction remodeling along Hyderabad outskirts.',
      },
    ],
  },
  {
    id: 'bu-buildings',
    code: 'MEIL-BLDG',
    name: 'Buildings & Industrial Infrastructure',
    shortName: 'Buildings & Infra',
    subsidiaryCode: 'MEIL-INFRA',
    subsidiaryName: 'MEIL Infrastructure',
    sector: 'Healthcare, Institutions & Smart Factories',
    iconName: 'Building2',
    accentColor: '#10B981',
    gradient: 'from-emerald-500 to-teal-600',
    description: 'Medical colleges, hospital complexes, institutional campuses, and clean EV manufacturing facilities.',
    projects: [
      { id: 'bldg-01', code: 'MEIL-BD-MCP', name: 'Machilipatnam Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'ACTIVE', esgScore: 91, brsrCore: true, reportingOwner: 'Er. V. Murthy', description: 'Comprehensive state-of-the-art 500-bed teaching hospital and educational facility.' },
      { id: 'bldg-02', code: 'MEIL-BD-ELR', name: 'Eluru Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'IN_OPERATION', esgScore: 93, brsrCore: true, reportingOwner: 'Er. K. Sastry', description: 'Advanced tertiary healthcare facility and academic blocks constructed with IGBC green norms.' },
      { id: 'bldg-03', code: 'MEIL-BD-RJY', name: 'Rajahmundry Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'ACTIVE', esgScore: 89, brsrCore: true, reportingOwner: 'Er. L. Naidu', description: 'Modern government medical institute catering to the East Godavari region.' },
      { id: 'bldg-04', code: 'MEIL-BD-PDG', name: 'Piduguralla Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'ACTIVE', esgScore: 88, brsrCore: true, reportingOwner: 'Er. N. Rao', description: 'Multispecialty healthcare complex supporting rural and semi-urban populations.' },
      { id: 'bldg-05', code: 'MEIL-BD-MDP', name: 'Madanapalle Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'ACTIVE', esgScore: 90, brsrCore: true, reportingOwner: 'Er. S. Reddy', description: 'Tertiary healthcare and research university campus with energy-efficient building envelope.' },
      { id: 'bldg-06', code: 'MEIL-BD-ATP', name: 'Anantapur Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'IN_OPERATION', esgScore: 92, brsrCore: true, reportingOwner: 'Er. J. Mohan', description: 'Healthcare hospital expansion with surgical suites, solar panels, and water treatment plants.' },
      { id: 'bldg-07', code: 'MEIL-BD-AMP', name: 'Amalapuram Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'ACTIVE', esgScore: 87, brsrCore: true, reportingOwner: 'Er. H. Verma', description: 'Institutional campus delivering medical education and subsidized patient healthcare.' },
      { id: 'bldg-08', code: 'MEIL-BD-PLK', name: 'Palakollu Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'ACTIVE', esgScore: 88, brsrCore: true, reportingOwner: 'Er. Y. Babu', description: 'State healthcare infrastructure project featuring water-recharge and zero-waste systems.' },
      { id: 'bldg-09', code: 'MEIL-BD-BPT', name: 'Bapatla Medical College', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Medical College & Hospital', status: 'ACTIVE', esgScore: 89, brsrCore: true, reportingOwner: 'Er. F. Khan', description: 'Modern medical campus serving coastal agricultural populations with advanced care.' },
      { id: 'bldg-10', code: 'MEIL-BD-NIM', name: 'NIMS Expansion Project', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Super-Specialty Hospital Block', status: 'ACTIVE', esgScore: 95, brsrCore: true, reportingOwner: 'Er. T. Rao', description: '2,000-bed super-specialty hospital tower at Nizam’s Institute of Medical Sciences, Hyderabad.' },
      { id: 'bldg-11', code: 'MEIL-BD-TMS', name: 'Sanathnagar Hospital / TIMS', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Hyderabad, Telangana', stateOrCountry: 'Telangana', category: 'Institute of Medical Sciences', status: 'ACTIVE', esgScore: 94, brsrCore: true, reportingOwner: 'Er. P. Krishna', description: 'Flagship Telangana Institute of Medical Sciences (TIMS) super-specialty institution.' },
      { id: 'bldg-12', code: 'MEIL-BD-OSH', name: 'Osmania Hospital Redevelopment', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Hyderabad, Telangana', stateOrCountry: 'Telangana', category: 'Heritage Hospital Modernization', status: 'ACTIVE', esgScore: 91, brsrCore: true, reportingOwner: 'Er. R. Chander', description: 'Heritage-sensitive modern hospital campus redevelopment with world-class trauma care.' },
      { id: 'bldg-13', code: 'MEIL-BD-OLE', name: 'Olectra Bus Manufacturing Facility', buId: 'bu-buildings', buName: 'Buildings & Industrial Infrastructure', location: 'Hyderabad, Telangana', stateOrCountry: 'Telangana', category: 'Clean EV Gigafactory', status: 'IN_OPERATION', esgScore: 97, brsrCore: true, reportingOwner: 'Er. A. Narang', description: 'India’s largest pure-electric bus and heavy EV manufacturing plant with zero liquid discharge.' },
    ],
  },
  {
    id: 'bu-hydrocarbons',
    code: 'MEIL-HYDRO',
    name: 'Hydrocarbons',
    shortName: 'Hydrocarbons',
    subsidiaryCode: 'MEIL-HYDRO',
    subsidiaryName: 'MEIL Hydrocarbons & Energy',
    sector: 'Refineries, Petrochemicals & Strategic Reserves',
    iconName: 'Flame',
    accentColor: '#F59E0B',
    gradient: 'from-amber-500 to-orange-600',
    description: 'High-complexity refinery units, cross-country gas pipelines, and underground strategic petroleum reserves.',
    projects: [
      { id: 'hydro-01', code: 'MEIL-HC-MNG', name: 'Mongolia Greenfield Crude Oil Refinery', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Mongolia', stateOrCountry: 'Mongolia', category: 'International Crude Refinery', status: 'ACTIVE', esgScore: 89, brsrCore: true, reportingOwner: 'Er. S. Batra', description: 'Landmark bilateral project constructing Mongolia’s first domestic oil refinery.' },
      { id: 'hydro-02', code: 'MEIL-HC-HRR', name: 'HPCL Rajasthan Refinery — Process Units', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Rajasthan', stateOrCountry: 'Rajasthan', category: 'Refinery Process Packages', status: 'ACTIVE', esgScore: 91, brsrCore: true, reportingOwner: 'Er. M. Jain', description: 'Execution of multiple core process units for the greenfield Barmer refinery.' },
      { id: 'hydro-03', code: 'MEIL-HC-PPU', name: 'Rajasthan Refinery Polypropylene Unit', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Rajasthan', stateOrCountry: 'Rajasthan', category: 'Petrochemical Complex', status: 'ACTIVE', esgScore: 90, brsrCore: true, reportingOwner: 'Er. K. Bansal', description: 'State-of-the-art polymer manufacturing facility maximizing downstream crude value.' },
      { id: 'hydro-04', code: 'MEIL-HC-BT1', name: 'Rajasthan Refinery Butene-1 Unit', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Rajasthan', stateOrCountry: 'Rajasthan', category: 'Chemical Synthesis Unit', status: 'ACTIVE', esgScore: 89, brsrCore: true, reportingOwner: 'Er. D. Sen', description: 'Specialized chemical co-monomer synthesis unit for high-grade polyethylene manufacture.' },
      { id: 'hydro-05', code: 'MEIL-HC-LPE', name: 'Rajasthan Refinery LLDPE/HDPE Unit', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Rajasthan', stateOrCountry: 'Rajasthan', category: 'Polymer Extrusion Plant', status: 'ACTIVE', esgScore: 92, brsrCore: true, reportingOwner: 'Er. R. Mathur', description: 'Dual-line polyethylene plant built with high energy-efficiency ratings.' },
      { id: 'hydro-06', code: 'MEIL-HC-ABN', name: 'Barmer ABNP Surface Facilities', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Barmer, Rajasthan', stateOrCountry: 'Rajasthan', category: 'Wellhead Surface Facilities', status: 'IN_OPERATION', esgScore: 88, brsrCore: true, reportingOwner: 'Er. O. Rathore', description: 'Upstream oil and gas field surface processing and separation manifolds.' },
      { id: 'hydro-07', code: 'MEIL-HC-PRU', name: 'Vadodara Propylene Recovery Unit', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Vadodara, Gujarat', stateOrCountry: 'Gujarat', category: 'Propylene Fractionation', status: 'IN_OPERATION', esgScore: 93, brsrCore: true, reportingOwner: 'Er. C. Patel', description: 'High-purity propylene fractionation unit operating under closed-loop emission controls.' },
      { id: 'hydro-08', code: 'MEIL-HC-PAD', name: 'Padur Strategic Petroleum Reserve', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Karnataka', stateOrCountry: 'Karnataka', category: 'Underground Rock Caverns', status: 'IN_OPERATION', esgScore: 95, brsrCore: true, reportingOwner: 'Er. U. Shetty', description: 'Subterranean unlined rock caverns for national energy security reserves.' },
      { id: 'hydro-09', code: 'MEIL-HC-GLK', name: 'Geleki Pipeline', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Assam', stateOrCountry: 'Assam', category: 'Cross-Terrain Crude Pipeline', status: 'IN_OPERATION', esgScore: 87, brsrCore: true, reportingOwner: 'Er. B. Saikia', description: 'High-integrity pipeline traversing challenging riverbed terrain in upper Assam.' },
      { id: 'hydro-10', code: 'MEIL-HC-GJP', name: 'Gojalia–Paltana Pipeline', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Tripura', stateOrCountry: 'Tripura', category: 'High-Pressure Gas Pipeline', status: 'IN_OPERATION', esgScore: 89, brsrCore: true, reportingOwner: 'Er. T. Debbarma', description: 'Natural gas pipeline feeding the 726 MW clean thermal combined-cycle plant.' },
      { id: 'hydro-11', code: 'MEIL-HC-GMW', name: 'Gamnewala Pipeline', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Rajasthan', stateOrCountry: 'Rajasthan', category: 'Desert Gas Pipeline', status: 'IN_OPERATION', esgScore: 86, brsrCore: true, reportingOwner: 'Er. I. Bishnoi', description: 'Harsh Thar desert pipeline network equipped with optical leak detection sensors.' },
      { id: 'hydro-12', code: 'MEIL-HC-AZR', name: 'Al-Zour Refinery Works', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Kuwait', stateOrCountry: 'Kuwait', category: 'Middle East Mega Refinery', status: 'IN_OPERATION', esgScore: 91, brsrCore: true, reportingOwner: 'Er. M. Al-Farooq', description: 'Piping, electrical and mechanical execution at Kuwait’s 615,000 bpd clean fuels refinery.' },
      { id: 'hydro-13', code: 'MEIL-HC-APP', name: 'Arab Potash Gas Power Plant', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Jordan', stateOrCountry: 'Jordan', category: 'Industrial Gas Co-Gen', status: 'IN_OPERATION', esgScore: 90, brsrCore: true, reportingOwner: 'Er. N. Haddad', description: 'High-efficiency industrial cogeneration gas-based power station at the Dead Sea.' },
      { id: 'hydro-14', code: 'MEIL-HC-BRN', name: 'Barauni Refinery Process Works', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Bihar', stateOrCountry: 'Bihar', category: 'Refinery Modernization', status: 'ACTIVE', esgScore: 88, brsrCore: true, reportingOwner: 'Er. K. Jha', description: 'Expansion units to produce BS-VI compliant transportation fuels.' },
      { id: 'hydro-15', code: 'MEIL-HC-PRD', name: 'Paradip Refinery Process Works', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Odisha', stateOrCountry: 'Odisha', category: 'Coastal Refinery Package', status: 'ACTIVE', esgScore: 89, brsrCore: true, reportingOwner: 'Er. S. Mohanty', description: 'Cyclic catalytic reforming and isomerization process units on the eastern seaboard.' },
      { id: 'hydro-16', code: 'MEIL-HC-GJR', name: 'Gujarat Refinery Process Works', buId: 'bu-hydrocarbons', buName: 'Hydrocarbons', location: 'Gujarat', stateOrCountry: 'Gujarat', category: 'Downstream Enhancement', status: 'ACTIVE', esgScore: 91, brsrCore: true, reportingOwner: 'Er. P. Mehta', description: 'Revamp and capacity expansion packages with advanced flare gas recovery.' },
    ],
  },
  {
    id: 'bu-renewable',
    code: 'MEIL-RENEW',
    name: 'Renewable Energy',
    shortName: 'Renewables',
    subsidiaryCode: 'MEIL-POWER',
    subsidiaryName: 'MEIL Power Systems',
    sector: 'Solar PV, Canal-Top Solar & Green Feeder Networks',
    iconName: 'SunMedium',
    accentColor: '#0EA5E9',
    gradient: 'from-sky-400 to-cyan-600',
    description: 'Utility-scale solar farms, innovative canal-top solar generation, and PM-KUSUM agricultural solarization.',
    projects: [
      { id: 'renew-01', code: 'MEIL-RE-STP', name: 'Anantapur Solar Thermal Power Plant', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Solar Thermal / CSP', status: 'IN_OPERATION', esgScore: 98, brsrCore: true, reportingOwner: 'Er. A. Chandra', description: 'Concentrated solar power installation displacing 120,000 tCO2e annually.' },
      { id: 'renew-02', code: 'MEIL-RE-CTS', name: 'Vadodara Canal-Top Solar Project', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Gujarat', stateOrCountry: 'Gujarat', category: 'Canal-Top Solar PV', status: 'IN_OPERATION', esgScore: 99, brsrCore: true, reportingOwner: 'Er. R. Somani', description: 'Pioneering canal-top panels preventing water evaporation while generating green electricity.' },
      { id: 'renew-03', code: 'MEIL-RE-SKR', name: 'Sakri Solar Power Project', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Utility Scale Solar', status: 'IN_OPERATION', esgScore: 96, brsrCore: true, reportingOwner: 'Er. G. Shinde', description: 'Grid-connected multi-megawatt photovoltaic park on non-arable land.' },
      { id: 'renew-04', code: 'MEIL-RE-KSM', name: 'PM-KUSUM Feeder Solarisation (MH)', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Agricultural Solar Grid', status: 'ACTIVE', esgScore: 95, brsrCore: true, reportingOwner: 'Er. P. Deshpande', description: 'Decentralized solar agricultural feeders delivering daytime green power to farmers.' },
      { id: 'renew-05', code: 'MEIL-RE-KSK', name: 'PM-KUSUM Feeder Solarisation (KA)', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Karnataka', stateOrCountry: 'Karnataka', category: 'Agricultural Solar Grid', status: 'ACTIVE', esgScore: 95, brsrCore: true, reportingOwner: 'Er. S. Gowda', description: 'Rural agricultural feeder decarbonization supporting sustainable irrigation.' },
      { id: 'renew-06', code: 'MEIL-RE-NYK', name: 'Nayakanhati Solar Project', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Karnataka', stateOrCountry: 'Karnataka', category: 'Solar Photovoltaic', status: 'IN_OPERATION', esgScore: 94, brsrCore: true, reportingOwner: 'Er. M. Murthy', description: 'High-yield solar farm equipped with single-axis tracking systems.' },
      { id: 'renew-07', code: 'MEIL-RE-NLR', name: 'Nallur Solar Project', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Karnataka', stateOrCountry: 'Karnataka', category: 'Solar Photovoltaic', status: 'IN_OPERATION', esgScore: 93, brsrCore: true, reportingOwner: 'Er. V. Kulkarni', description: 'Clean energy generation supplying regional grid substations.' },
      { id: 'renew-08', code: 'MEIL-RE-VLH', name: 'Vilhale Solar Project', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Solar Photovoltaic', status: 'IN_OPERATION', esgScore: 94, brsrCore: true, reportingOwner: 'Er. D. Jadhav', description: 'Grid-tied solar installation generating verified carbon offsets.' },
      { id: 'renew-09', code: 'MEIL-RE-BOR', name: 'Bori Solar Project', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Solar Photovoltaic', status: 'IN_OPERATION', esgScore: 92, brsrCore: true, reportingOwner: 'Er. T. Wagh', description: 'Photovoltaic farm with automated dry-robot cleaning conserving local water.' },
      { id: 'renew-10', code: 'MEIL-RE-WRK', name: 'Warkhedi Solar Project', buId: 'bu-renewable', buName: 'Renewable Energy', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Solar Photovoltaic', status: 'IN_OPERATION', esgScore: 93, brsrCore: true, reportingOwner: 'Er. B. Thorat', description: 'Zero-emission solar power plant connected to the state transmission network.' },
    ],
  },
  {
    id: 'bu-power',
    code: 'MEIL-PWR',
    name: 'Power',
    shortName: 'Power & Grid',
    subsidiaryCode: 'MEIL-POWER',
    subsidiaryName: 'MEIL Power Systems',
    sector: 'Pumped Hydro, Nuclear & GIS Substations',
    iconName: 'Zap',
    accentColor: '#6366F1',
    gradient: 'from-indigo-500 to-blue-700',
    description: 'Pumped storage hydroelectricity, nuclear balance of plant, GIS substations, and interstate transmission lines.',
    projects: [
      { id: 'pwr-01', code: 'MEIL-PW-TUT', name: 'Tuticorin Thermal Power Project', buId: 'bu-power', buName: 'Power', location: 'Tamil Nadu', stateOrCountry: 'Tamil Nadu', category: 'Thermal Energy', status: 'IN_OPERATION', esgScore: 84, brsrCore: true, reportingOwner: 'Er. G. Selvam', description: 'Coastal supercritical thermal plant featuring seawater flue-gas desulfurization.' },
      { id: 'pwr-02', code: 'MEIL-PW-NEY', name: 'Neyveli Energy Project', buId: 'bu-power', buName: 'Power', location: 'Tamil Nadu', stateOrCountry: 'Tamil Nadu', category: 'Thermal Energy', status: 'IN_OPERATION', esgScore: 86, brsrCore: true, reportingOwner: 'Er. K. Balaji', description: 'Lignite-to-power generation station with high-efficiency electrostatic precipitators.' },
      { id: 'pwr-03', code: 'MEIL-PW-KND', name: 'Kundah Pumped Storage Project', buId: 'bu-power', buName: 'Power', location: 'Tamil Nadu', stateOrCountry: 'Tamil Nadu', category: 'Pumped Storage Hydro', status: 'ACTIVE', esgScore: 97, brsrCore: true, reportingOwner: 'Er. R. Venkatesh', description: '500 MW underground pumped hydro storage stabilizing Southern regional grid fluctuations.' },
      { id: 'pwr-04', code: 'MEIL-PW-UPS', name: 'Upper Sileru Pumped Storage', buId: 'bu-power', buName: 'Power', location: 'Andhra Pradesh / Odisha', stateOrCountry: 'Andhra Pradesh', category: 'Pumped Storage Hydro', status: 'ACTIVE', esgScore: 96, brsrCore: true, reportingOwner: 'Er. P. Patnaik', description: 'Mega pumped-hydro peaking plant utilizing natural elevation difference.' },
      { id: 'pwr-05', code: 'MEIL-PW-SND', name: 'Saundatti Pumped Storage Project', buId: 'bu-power', buName: 'Power', location: 'Karnataka', stateOrCountry: 'Karnataka', category: 'Pumped Storage Hydro', status: 'ACTIVE', esgScore: 95, brsrCore: true, reportingOwner: 'Er. L. Patil', description: 'Closed-loop pumped storage battery plant providing 1,200 MW rapid-dispatch power.' },
      { id: 'pwr-06', code: 'MEIL-PW-KMD', name: 'Kamod Pumped Storage Project', buId: 'bu-power', buName: 'Power', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Pumped Storage Hydro', status: 'ACTIVE', esgScore: 94, brsrCore: true, reportingOwner: 'Er. A. Kadam', description: 'Grid energy storage reservoir mitigating solar-wind intermittency.' },
      { id: 'pwr-07', code: 'MEIL-PW-GHS', name: 'Ghosla Pumped Storage Project', buId: 'bu-power', buName: 'Power', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Pumped Storage Hydro', status: 'ACTIVE', esgScore: 93, brsrCore: true, reportingOwner: 'Er. M. Shinde', description: 'Western ghats elevation hydro storage enabling round-the-clock green power.' },
      { id: 'pwr-08', code: 'MEIL-PW-RAT', name: 'Ratle Hydroelectric Project', buId: 'bu-power', buName: 'Power', location: 'Jammu & Kashmir', stateOrCountry: 'Jammu & Kashmir', category: 'Run-of-the-River Hydro', status: 'ACTIVE', esgScore: 95, brsrCore: true, reportingOwner: 'Er. I. Ahmad', description: '850 MW run-of-the-river hydroelectric scheme on the Chenab river.' },
      { id: 'pwr-09', code: 'MEIL-PW-POL', name: 'Polavaram Hydro Power Project', buId: 'bu-power', buName: 'Power', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Dam-Toe Hydro Station', status: 'ACTIVE', esgScore: 96, brsrCore: true, reportingOwner: 'Er. S. Rao', description: '960 MW clean hydroelectric power station integrated into Polavaram multipurpose dam.' },
      { id: 'pwr-10', code: 'MEIL-PW-KGA', name: 'Kaiga Nuclear Power Project, Units 5 & 6', buId: 'bu-power', buName: 'Power', location: 'Karnataka', stateOrCountry: 'Karnataka', category: 'Nuclear Clean Energy', status: 'ACTIVE', esgScore: 98, brsrCore: true, reportingOwner: 'Er. V. Bhatt', description: 'Balance-of-plant and cooling systems for 2x700 MW indigenous Pressurized Heavy Water Reactors.' },
      { id: 'pwr-11', code: 'MEIL-PW-TRW', name: 'Tirwa Transmission Project', buId: 'bu-power', buName: 'Power', location: 'Uttar Pradesh', stateOrCountry: 'Uttar Pradesh', category: 'High-Voltage Transmission', status: 'IN_OPERATION', esgScore: 89, brsrCore: true, reportingOwner: 'Er. R. Tiwari', description: '400 kV extra-high-voltage power evacuation lines.' },
      { id: 'pwr-12', code: 'MEIL-PW-MSH', name: 'Meerut–Shamli Transmission Project', buId: 'bu-power', buName: 'Power', location: 'Uttar Pradesh', stateOrCountry: 'Uttar Pradesh', category: 'Inter-Grid Line', status: 'IN_OPERATION', esgScore: 90, brsrCore: true, reportingOwner: 'Er. S. Malik', description: 'Heavy transmission backbone facilitating regional grid balancing.' },
      { id: 'pwr-13', code: 'MEIL-PW-KSH', name: 'Kushtagi Substation & Line', buId: 'bu-power', buName: 'Power', location: 'Karnataka', stateOrCountry: 'Karnataka', category: 'Substation & T&D', status: 'IN_OPERATION', esgScore: 91, brsrCore: true, reportingOwner: 'Er. H. Nayak', description: 'Wind and solar pooling substation evacuating renewable energy.' },
      { id: 'pwr-14', code: 'MEIL-PW-JUS', name: 'JUSNL Patratu–Chandil Line', buId: 'bu-power', buName: 'Power', location: 'Jharkhand', stateOrCountry: 'Jharkhand', category: 'Transmission Corridor', status: 'IN_OPERATION', esgScore: 88, brsrCore: true, reportingOwner: 'Er. K. Soren', description: 'Vital industrial corridor connecting thermal generation to manufacturing plants.' },
      { id: 'pwr-15', code: 'MEIL-PW-VRD', name: 'Virudhunagar Substation', buId: 'bu-power', buName: 'Power', location: 'Tamil Nadu', stateOrCountry: 'Tamil Nadu', category: '765 kV Super Grid Station', status: 'ACTIVE', esgScore: 93, brsrCore: true, reportingOwner: 'Er. T. Pandian', description: 'Southern grid interstate transmission hub handling bulk renewable flows.' },
      { id: 'pwr-16', code: 'MEIL-PW-YAD', name: 'Yadadri–Choutuppal Corridor', buId: 'bu-power', buName: 'Power', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Transmission Corridor', status: 'ACTIVE', esgScore: 91, brsrCore: true, reportingOwner: 'Er. N. Goud', description: 'Evacuation transmission link for the Yadadri Mega Thermal Power Station.' },
      { id: 'pwr-17', code: 'MEIL-PW-NPK', name: 'NP Kunta Substation', buId: 'bu-power', buName: 'Power', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Solar Pooling Substation', status: 'IN_OPERATION', esgScore: 94, brsrCore: true, reportingOwner: 'Er. C. Reddy', description: 'Interconnection pooling yard for the 1,500 MW Ultra Mega Solar Park.' },
      { id: 'pwr-18', code: 'MEIL-PW-RAI', name: 'GIS Raidurg Substation', buId: 'bu-power', buName: 'Power', location: 'Hyderabad, Telangana', stateOrCountry: 'Telangana', category: 'Gas Insulated Substation', status: 'IN_OPERATION', esgScore: 96, brsrCore: true, reportingOwner: 'Er. M. Srinivas', description: 'Compact underground GIS station feeding Hyderabad IT corridor with high reliability.' },
      { id: 'pwr-19', code: 'MEIL-PW-GDV', name: 'Gudivada Substation', buId: 'bu-power', buName: 'Power', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: '220 kV Grid Substation', status: 'IN_OPERATION', esgScore: 90, brsrCore: true, reportingOwner: 'Er. B. Ramesh', description: 'Power transmission substation powering coastal irrigation pumps and towns.' },
      { id: 'pwr-20', code: 'MEIL-PW-ACH', name: 'Achutapuram GIS Substation', buId: 'bu-power', buName: 'Power', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Industrial GIS Station', status: 'IN_OPERATION', esgScore: 93, brsrCore: true, reportingOwner: 'Er. E. Raju', description: 'High-reliability GIS plant serving Special Economic Zones and heavy industries.' },
      { id: 'pwr-21', code: 'MEIL-PW-AIN', name: 'Ainavilli Substation', buId: 'bu-power', buName: 'Power', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Delta Distribution Substation', status: 'IN_OPERATION', esgScore: 89, brsrCore: true, reportingOwner: 'Er. S. Rao', description: 'Modern rural electrification and storm-hardened coastal grid hub.' },
    ],
  },
  {
    id: 'bu-water',
    code: 'MEIL-WATER',
    name: 'Water / Drinking Water',
    shortName: 'Drinking Water',
    subsidiaryCode: 'MEIL-INFRA',
    subsidiaryName: 'MEIL Infrastructure',
    sector: 'Piped Water Grids, Water Treatment & STPs',
    iconName: 'Droplets',
    accentColor: '#06B6D4',
    gradient: 'from-cyan-500 to-blue-600',
    description: 'Statewide rural piped potable water grids, urban bulk treatment facilities, and advanced sewage treatment plants.',
    projects: [
      { id: 'wtr-01', code: 'MEIL-WT-BHG', name: 'Mission Bhagiratha', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Statewide Piped Water Grid', status: 'IN_OPERATION', esgScore: 99, brsrCore: true, reportingOwner: 'Er. K. Chandran', description: 'Transformational 130,000 km water grid delivering treated potable tap water to 25,000 villages.' },
      { id: 'wtr-02', code: 'MEIL-WT-GDV', name: 'Godavari Drinking Water Supply', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Hyderabad, Telangana', stateOrCountry: 'Telangana', category: 'Metropolitan Water Supply', status: 'IN_OPERATION', esgScore: 97, brsrCore: true, reportingOwner: 'Er. S. Varma', description: 'Bulk water lift and intake project quenching drinking water demand of greater Hyderabad.' },
      { id: 'wtr-03', code: 'MEIL-WT-UDD', name: 'Uddanam Drinking Water Project', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Kidney-Safe Water Supply', status: 'IN_OPERATION', esgScore: 98, brsrCore: true, reportingOwner: 'Er. P. Mohana', description: 'Pure water filtration grid tackling chronic kidney disease across 800+ coastal villages.' },
      { id: 'wtr-04', code: 'MEIL-WT-AGB', name: 'Aurangabad Water Supply Project', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Municipal Bulk Water', status: 'ACTIVE', esgScore: 92, brsrCore: true, reportingOwner: 'Er. D. Gaikwad', description: 'Intake and pipeline project ensuring round-the-clock water to 2 million urban citizens.' },
      { id: 'wtr-05', code: 'MEIL-WT-LTR', name: 'Latur Water Supply Project', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Maharashtra', stateOrCountry: 'Maharashtra', category: 'Drought Resilience Water Grid', status: 'IN_OPERATION', esgScore: 94, brsrCore: true, reportingOwner: 'Er. V. Joshi', description: 'Permanent water conveyance scheme overcoming decades of extreme Marathwada drought.' },
      { id: 'wtr-06', code: 'MEIL-WT-GJY', name: 'Ganga Jal Aapurti Yojana', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Bihar', stateOrCountry: 'Bihar', category: 'Floodwater Harvest & Water Supply', status: 'IN_OPERATION', esgScore: 97, brsrCore: true, reportingOwner: 'Er. A. Kumar', description: 'Harvesting surplus floodwaters from the Ganga to supply purified drinking water to Rajgir, Gaya, and Bodh Gaya.' },
      { id: 'wtr-07', code: 'MEIL-WT-BBS', name: 'Bhubaneswar Bulk Water Supply', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Odisha', stateOrCountry: 'Odisha', category: 'Urban Water Treatment', status: 'IN_OPERATION', esgScore: 93, brsrCore: true, reportingOwner: 'Er. S. Das', description: 'High-capacity rapid gravity filtration plant supplying capital smart city zones.' },
      { id: 'wtr-08', code: 'MEIL-WT-PL3', name: 'Pillur III Water Supply Project', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Tamil Nadu', stateOrCountry: 'Tamil Nadu', category: 'Regional Piped Water', status: 'IN_OPERATION', esgScore: 91, brsrCore: true, reportingOwner: 'Er. M. Ramanathan', description: 'Dedicated pipeline and water treatment infrastructure serving Coimbatore municipal area.' },
      { id: 'wtr-09', code: 'MEIL-WT-NLR', name: 'Nellore Water Supply Schemes', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Comprehensive Water Network', status: 'IN_OPERATION', esgScore: 89, brsrCore: true, reportingOwner: 'Er. B. Naidu', description: 'River intake, clarification, and overhead balancing reservoirs.' },
      { id: 'wtr-10', code: 'MEIL-WT-PRD', name: 'Proddatur Water Supply Scheme', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Urban Water Scheme', status: 'IN_OPERATION', esgScore: 88, brsrCore: true, reportingOwner: 'Er. K. Sivaram', description: 'Modernized pressurized distribution lines minimizing water transmission leakage.' },
      { id: 'wtr-11', code: 'MEIL-WT-PLV', name: 'Pulivendula Water Supply Scheme', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Semi-Arid Water Supply', status: 'IN_OPERATION', esgScore: 90, brsrCore: true, reportingOwner: 'Er. T. Reddeppa', description: 'Groundwater replenishment and canal-fed filtration facilities.' },
      { id: 'wtr-12', code: 'MEIL-WT-STP', name: 'Hyderabad Sewage Treatment Plants', buId: 'bu-water', buName: 'Water / Drinking Water', location: 'Hyderabad, Telangana', stateOrCountry: 'Telangana', category: 'Urban Wastewater & SBR STPs', status: 'ACTIVE', esgScore: 96, brsrCore: true, reportingOwner: 'Er. L. Harish', description: 'Multi-package Sequencing Batch Reactor (SBR) STPs treating 100% of municipal wastewater to river discharge standards.' },
    ],
  },
  {
    id: 'bu-irrigation',
    code: 'MEIL-IRRIG',
    name: 'Irrigation',
    shortName: 'Irrigation',
    subsidiaryCode: 'MEIL-INFRA',
    subsidiaryName: 'MEIL Infrastructure',
    sector: 'Lift Irrigation, Pumphouses & River Linking',
    iconName: 'Waves',
    accentColor: '#14B8A6',
    gradient: 'from-teal-500 to-emerald-600',
    description: 'The world’s largest multi-stage lift irrigation schemes, massive underground pumphouses, and smart drip irrigation systems.',
    projects: [
      { id: 'irrig-01', code: 'MEIL-IR-KLS', name: 'Kaleshwaram Lift Irrigation Project', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'World’s Largest Lift Irrigation Scheme', status: 'IN_OPERATION', esgScore: 98, brsrCore: true, reportingOwner: 'Er. B. Srinivas Rao', description: 'Engineering marvel lifting 2 TMC Godavari water per day across 500+ meters elevation.' },
      { id: 'irrig-02', code: 'MEIL-IR-GYT', name: 'Gayatri Pumphouse — Kaleshwaram', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Kaleshwaram, Telangana', stateOrCountry: 'Telangana', category: 'Underground Mega Pumphouse', status: 'IN_OPERATION', esgScore: 99, brsrCore: true, reportingOwner: 'Er. K. V. Sharma', description: 'Asia’s deepest underground pumphouse housing seven 139 MW world-record pump units.' },
      { id: 'irrig-03', code: 'MEIL-IR-POL', name: 'Polavaram Project', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'National Multipurpose Dam', status: 'ACTIVE', esgScore: 95, brsrCore: true, reportingOwner: 'Er. R. Anjaneyulu', description: 'Multipurpose Godavari river reservoir irrigating 720,000 acres and interlinking river basins.' },
      { id: 'irrig-04', code: 'MEIL-IR-RMT', name: 'Ramthal Drip Irrigation Project', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Karnataka', stateOrCountry: 'Karnataka', category: 'Asia’s Largest Automated Drip System', status: 'IN_OPERATION', esgScore: 99, brsrCore: true, reportingOwner: 'Er. H. Nadagouda', description: 'Pressurized smart drip irrigation conserving 50% water across 12,300+ farmer holdings.' },
      { id: 'irrig-05', code: 'MEIL-IR-PRL', name: 'Palamuru–Rangareddy Lift Irrigation', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'High-Head Lift Irrigation', status: 'ACTIVE', esgScore: 94, brsrCore: true, reportingOwner: 'Er. G. Pratap', description: 'Massive lift project lifting Krishna water by 671 meters to drought-prone upland districts.' },
      { id: 'irrig-06', code: 'MEIL-IR-STR', name: 'Sita Rama Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Lift Canal Network', status: 'ACTIVE', esgScore: 92, brsrCore: true, reportingOwner: 'Er. J. Prabhakar', description: 'Stabilizing irrigation over 6.7 lakh acres in Bhadradri Kothagudem and Khammam.' },
      { id: 'irrig-07', code: 'MEIL-IR-MLK', name: 'Malkapet Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Tributary Water Lift', status: 'IN_OPERATION', esgScore: 91, brsrCore: true, reportingOwner: 'Er. S. Tirupathi', description: 'Pumphouses and gravity delivery cisterns energizing Rajanna Sircilla farm lands.' },
      { id: 'irrig-08', code: 'MEIL-IR-MNJ', name: 'Manjeera Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'River Lift Irrigation', status: 'IN_OPERATION', esgScore: 90, brsrCore: true, reportingOwner: 'Er. D. Mallesh', description: 'Pumping system stabilizing ayacuts along the Manjeera river basin.' },
      { id: 'irrig-09', code: 'MEIL-IR-GDL', name: 'Godavari Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Multi-Stage Pumping', status: 'IN_OPERATION', esgScore: 93, brsrCore: true, reportingOwner: 'Er. T. Satyanarayana', description: 'Early generation lift irrigation installations pioneering high-discharge pumping.' },
      { id: 'irrig-10', code: 'MEIL-IR-BSV', name: 'Basaveswaram Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Upland Lift Scheme', status: 'ACTIVE', esgScore: 89, brsrCore: true, reportingOwner: 'Er. R. Shekar', description: 'Lifting waters to high altitude plateaus to transform semi-arid scrub into fertile farmland.' },
      { id: 'irrig-11', code: 'MEIL-IR-NLK', name: 'Nellikal Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Reservoir Backwater Lift', status: 'ACTIVE', esgScore: 88, brsrCore: true, reportingOwner: 'Er. M. Lingaiah', description: 'Nagarjuna Sagar backwater lift bringing irrigation to tail-end agricultural zones.' },
      { id: 'irrig-12', code: 'MEIL-IR-AKB', name: 'AKBR Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Lift Irrigation Scheme', status: 'IN_OPERATION', esgScore: 90, brsrCore: true, reportingOwner: 'Er. C. Yadagiri', description: 'Ali Sagar and related lift schemes energizing Nizamabad district farm yields.' },
      { id: 'irrig-13', code: 'MEIL-IR-DND', name: 'Dindi Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Fluoride-Affected Ayacut Lift', status: 'ACTIVE', esgScore: 92, brsrCore: true, reportingOwner: 'Er. B. Ravinder', description: 'Providing both irrigation and drinking replenishment in severe fluoride zones of Nalgonda.' },
      { id: 'irrig-14', code: 'MEIL-IR-UDS', name: 'Udayasamudram Lift Irrigation', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Panagal Basin Lift', status: 'IN_OPERATION', esgScore: 89, brsrCore: true, reportingOwner: 'Er. P. Venkanna', description: 'Lift scheme serving dry-land farmers in Nalgonda with guaranteed canal water.' },
      { id: 'irrig-15', code: 'MEIL-IR-KLS2', name: 'Kalisindh Phase-2 Lift Irrigation', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Madhya Pradesh', stateOrCountry: 'Madhya Pradesh', category: 'Pressurized Pipe Irrigation', status: 'ACTIVE', esgScore: 93, brsrCore: true, reportingOwner: 'Er. V. Bundela', description: 'Pressurized underground pipe network supplying water up to farm gate level.' },
      { id: 'irrig-16', code: 'MEIL-IR-PNM', name: 'Panam Lift Irrigation Scheme', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Gujarat', stateOrCountry: 'Gujarat', category: 'Tribal Belt Lift Irrigation', status: 'IN_OPERATION', esgScore: 91, brsrCore: true, reportingOwner: 'Er. K. Baria', description: 'Lift scheme irrigating hilly tribal areas of Panchmahal and Mahisagar districts.' },
      { id: 'irrig-17', code: 'MEIL-IR-PR1', name: 'PRLIS-01', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Intake Pumphouse Package', status: 'ACTIVE', esgScore: 95, brsrCore: true, reportingOwner: 'Er. N. Janardhan', description: 'Package 1 of Palamuru lift scheme with heavy turbine pump erection.' },
      { id: 'irrig-18', code: 'MEIL-IR-PR5', name: 'PRLIS-05', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Telangana', stateOrCountry: 'Telangana', category: 'Reservoir Surge Pool Package', status: 'ACTIVE', esgScore: 94, brsrCore: true, reportingOwner: 'Er. E. Gopal', description: 'Package 5 involving subterranean tunnels, surge pools, and manifold pipes.' },
      { id: 'irrig-19', code: 'MEIL-IR-LSK', name: 'Lower Suktel Irrigation Project', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Odisha', stateOrCountry: 'Odisha', category: 'Dam & Canal System', status: 'ACTIVE', esgScore: 90, brsrCore: true, reportingOwner: 'Er. T. Sahu', description: 'Earth dam and spillway irrigating drought-prone Balangir and Subarnapur districts.' },
      { id: 'irrig-20', code: 'MEIL-IR-PTS', name: 'Pattiseema Lift Irrigation Project', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Andhra Pradesh', stateOrCountry: 'Andhra Pradesh', category: 'Limca Record River Linking Scheme', status: 'IN_OPERATION', esgScore: 98, brsrCore: true, reportingOwner: 'Er. M. Venkateswarlu', description: 'Built in a record 1 year to interlink Godavari and Krishna rivers, saving millions in Krishna delta crops.' },
      { id: 'irrig-21', code: 'MEIL-IR-NKS', name: 'Narmada–Kshipra–Simhastha Project', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Madhya Pradesh', stateOrCountry: 'Madhya Pradesh', category: 'River Interlinking Lift', status: 'IN_OPERATION', esgScore: 96, brsrCore: true, reportingOwner: 'Er. D. Malviya', description: 'Historic river interlink lifting Narmada waters over 350 meters to revive the Kshipra river.' },
      { id: 'irrig-22', code: 'MEIL-IR-NGB', name: 'Navnera–Galwa–Bisalpur–Isarda Canals', buId: 'bu-irrigation', buName: 'Irrigation', location: 'Rajasthan', stateOrCountry: 'Rajasthan', category: 'Eastern Rajasthan Canal Feeder', status: 'ACTIVE', esgScore: 93, brsrCore: true, reportingOwner: 'Er. C. Meena', description: 'Strategic feeder canal network rejuvenating drinking and irrigation supply in eastern Rajasthan.' },
    ],
  },
  {
    id: 'bu-ibd',
    code: 'MEIL-IBD',
    name: 'International Business Development (IBD)',
    shortName: 'International (IBD)',
    subsidiaryCode: 'MEIL-INFRA',
    subsidiaryName: 'MEIL Infrastructure',
    sector: 'Global Water, Cross-Border Infrastructures & Watersheds',
    iconName: 'Globe',
    accentColor: '#3B82F6',
    gradient: 'from-blue-600 to-indigo-700',
    description: 'International projects across Africa and Asia spanning trans-national water networks, irrigation, and refinery operations.',
    projects: [
      { id: 'ibd-01', code: 'MEIL-IB-LKV', name: 'Lake Victoria Water Supply Project', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Tanzania', stateOrCountry: 'Tanzania', category: 'Trans-National Water Intake', status: 'ACTIVE', esgScore: 97, brsrCore: true, reportingOwner: 'Er. J. Mwangi', description: 'Major water extraction and multi-town distribution pipeline tapping Lake Victoria.' },
      { id: 'ibd-02', code: 'MEIL-IB-KMB', name: 'Kiomboi Water Supply Works', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Tanzania', stateOrCountry: 'Tanzania', category: 'Municipal Piped Water', status: 'IN_OPERATION', esgScore: 94, brsrCore: true, reportingOwner: 'Er. E. Mrema', description: 'Comprehensive community water purification works eliminating water-borne illnesses.' },
      { id: 'ibd-03', code: 'MEIL-IB-SNG', name: 'Singida Water Supply Works', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Tanzania', stateOrCountry: 'Tanzania', category: 'Regional Water Scheme', status: 'IN_OPERATION', esgScore: 93, brsrCore: true, reportingOwner: 'Er. F. Massawe', description: 'Groundwater well-fields, solar booster pumps, and urban distribution pipes.' },
      { id: 'ibd-04', code: 'MEIL-IB-MNY', name: 'Manyoni Water Supply Works', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Tanzania', stateOrCountry: 'Tanzania', category: 'Town Water Supply', status: 'IN_OPERATION', esgScore: 91, brsrCore: true, reportingOwner: 'Er. D. Kimaro', description: 'Modern water storage tanks and reliable clean tap connectivity.' },
      { id: 'ibd-05', code: 'MEIL-IB-CHW', name: 'Chamwino Water Supply Works', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Tanzania', stateOrCountry: 'Tanzania', category: 'Government City Water Supply', status: 'IN_OPERATION', esgScore: 95, brsrCore: true, reportingOwner: 'Er. K. Makamba', description: 'Providing guaranteed potable supply to Tanzania’s national state capital zone.' },
      { id: 'ibd-06', code: 'MEIL-IB-CHM', name: 'Chemba Water Supply Works', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Tanzania', stateOrCountry: 'Tanzania', category: 'Rural Water Supply', status: 'IN_OPERATION', esgScore: 90, brsrCore: true, reportingOwner: 'Er. H. Swai', description: 'Sustainable solar-driven water pumps and village distribution kiosks.' },
      { id: 'ibd-07', code: 'MEIL-IB-MGM', name: 'Mugumu Water Supply Works', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Tanzania', stateOrCountry: 'Tanzania', category: 'Mara Region Water Works', status: 'IN_OPERATION', esgScore: 92, brsrCore: true, reportingOwner: 'Er. P. Lyimo', description: 'Water purification and gravity pipeline close to the Serengeti ecological zone.' },
      { id: 'ibd-08', code: 'MEIL-IB-DST', name: 'Dar-es-Salaam–Tabora Water Supply', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Tanzania', stateOrCountry: 'Tanzania', category: 'Trunk Water Pipeline', status: 'ACTIVE', esgScore: 96, brsrCore: true, reportingOwner: 'Er. A. Bakari', description: 'Strategic trans-provincial trunk main supplying rapidly expanding urban settlements.' },
      { id: 'ibd-09', code: 'MEIL-IB-MHM', name: 'Mahama Lot 1 Irrigation & Watershed', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Rwanda', stateOrCountry: 'Rwanda', category: 'Irrigation & Watershed Management', status: 'ACTIVE', esgScore: 98, brsrCore: true, reportingOwner: 'Er. P. Mugabo', description: 'UN-recognized watershed restoration, terrace soil conservation, and community drip irrigation.' },
      { id: 'ibd-10', code: 'MEIL-IB-ZNZ', name: 'Zanzibar Drinking Water Project', buId: 'bu-ibd', buName: 'International Business Development (IBD)', location: 'Zanzibar / Tanzania', stateOrCountry: 'Tanzania', category: 'Island Water Desal & Treatment', status: 'ACTIVE', esgScore: 95, brsrCore: true, reportingOwner: 'Er. Z. Khamis', description: 'Groundwater rehabilitation, saline intrusion barriers, and island potable water grid.' },
    ],
  },
]

/**
 * Helper utilities
 */
export function getAllBusinessUnits(): MeilBusinessUnit[] {
  return MEIL_BUSINESS_UNITS
}

export function getBusinessUnitById(id: string): MeilBusinessUnit | undefined {
  return MEIL_BUSINESS_UNITS.find(b => b.id === id || b.code === id)
}

export function getProjectsByBU(buId: string): MeilProject[] {
  const bu = getBusinessUnitById(buId)
  return bu ? bu.projects : []
}

export function getAllMeilProjects(): MeilProject[] {
  return MEIL_BUSINESS_UNITS.flatMap(b => b.projects)
}

export function getMeilProjectById(projectId: string): MeilProject | undefined {
  return getAllMeilProjects().find(p => p.id === projectId || p.code === projectId)
}
