import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getCurrentUser } from '@/lib/session'

export const runtime = 'nodejs'

// GET /api/reports/[id]/download — return the report content as a downloadable file.
//   - For data reports (EMISSIONS / ENERGY / WATER / WASTE / WORKFORCE / SAFETY
//     / ESG_SUMMARY / AUDIT_PACKAGE) → CSV.
//   - For BRSR → a structured plain-text rendition.
// Sets Content-Disposition: attachment; filename="..."
export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser()
  if (!user) return NextResponse.json({ error: 'Unauthenticated' }, { status: 401 })

  try {
    const { id } = await params
    const report = await db.report.findUnique({ where: { id } })
    if (!report) {
      return NextResponse.json({ error: 'Report not found' }, { status: 404 })
    }
    if (!report.content) {
      return NextResponse.json({ error: 'Report has no content' }, { status: 400 })
    }

    const fileName = report.fileName || `${report.reportType}-${report.id}.csv`
    let body: string
    let contentType: string

    if (report.reportType === 'BRSR') {
      const fs = await import('fs')
      const path = await import('path')

      // Use the exact official 14-page SEBI BRSR Annexure-I PDF provided
      const officialPdfCandidates = [
        path.join(process.cwd(), 'public', 'reports', 'MEIL-BRSR-Annexure-I-FY2026-v11.pdf'),
        path.join(process.cwd(), 'src', 'lib', 'meil-brsr-official.pdf'),
        'C:\\Users\\91814\\Downloads\\MEIL-BRSR-Annexure-I-FY2026-v11.pdf',
      ]

      let pdfBuffer: Buffer | null = null
      for (const candidate of officialPdfCandidates) {
        if (fs.existsSync(candidate)) {
          pdfBuffer = fs.readFileSync(candidate)
          break
        }
      }

      if (!pdfBuffer) {
        const { generateBrsrReportPdf } = await import('@/lib/brsr-pdf-generator')
        const pdfDoc = generateBrsrReportPdf({
          reportingYear: report.reportingYear ?? 2026,
          scopeName: report.scopeName ?? 'MEIL Group (All)',
          scopeType: report.scopeType ?? 'GROUP',
          generatedByName: report.generatedByName ?? 'Anita Desai (ESG / Sustainability Manager)',
          version: report.version,
        })
        pdfBuffer = Buffer.from(pdfDoc.output('arraybuffer'))
      }

      const pdfFileName = report.fileName?.endsWith('.pdf')
        ? report.fileName
        : `MEIL-BRSR-Annexure-I-FY${report.reportingYear ?? 2026}-v${report.version}.pdf`

      const isInline = req.nextUrl.searchParams.get('inline') === 'true'
      const disposition = isInline
        ? `inline; filename="${pdfFileName}"`
        : `attachment; filename="${pdfFileName}"; filename*=UTF-8''${encodeURIComponent(pdfFileName)}`

      const headers = new Headers()
      headers.set('Content-Type', 'application/pdf')
      headers.set('Content-Disposition', disposition)
      headers.set('Content-Length', String(pdfBuffer.byteLength))
      headers.set('Cache-Control', 'no-store')

      return new NextResponse(new Uint8Array(pdfBuffer), { status: 200, headers })
    }

    let parsed: any
    try {
      parsed = JSON.parse(report.content)
    } catch {
      parsed = { content: report.content }
    }
    body = jsonToCsv(parsed)
    contentType = 'text/csv; charset=utf-8'

    const headers = new Headers()
    headers.set('Content-Type', contentType)
    headers.set('Content-Disposition', `attachment; filename="${fileName}"`)
    headers.set('Cache-Control', 'no-store')

    return new NextResponse(body, { status: 200, headers })
  } catch (e: any) {
    return NextResponse.json({ error: 'Failed to download report', detail: String(e?.message ?? e) }, { status: 500 })
  }
}

// Render the BRSR content JSON into a readable plain-text report.
function renderBrsrText(raw: string): string {
  let parsed: any
  try { parsed = JSON.parse(raw) } catch { return raw }
  const lines: string[] = []
  const meta = parsed.meta ?? {}
  lines.push('========================================================')
  lines.push('  BRSR REPORT')
  lines.push('========================================================')
  if (meta.framework) {
    lines.push(`Framework:    ${meta.framework.name} ${meta.framework.version} (FY ${meta.framework.reportingYear})`)
    lines.push(`Tier:          ${meta.framework.tier}`)
  }
  lines.push(`Reporting Year: ${meta.reportingYear ?? 'N/A'}`)
  if (meta.scope) {
    lines.push(`Scope:         ${meta.scope.scopeType ?? '—'} / ${meta.scope.scopeName ?? meta.scope.scopeId ?? '—'}`)
  }
  lines.push(`Generated:     ${meta.generatedAt ?? new Date().toISOString()}`)
  if (meta.generatedBy) {
    lines.push(`Generated By:  ${meta.generatedBy.name} (${meta.generatedBy.roles?.join(', ') ?? ''})`)
  }
  lines.push(`Questions:     ${meta.totals?.questions ?? 0} (resolved from source: ${meta.totals?.resolvedFromSource ?? 0})`)
  if (parsed.readiness) {
    lines.push(`Readiness:     ${parsed.readiness.overallPct}% (${parsed.readiness.ready}/${parsed.readiness.total} answers ready)`)
  }
  lines.push('')
  const sections = Array.isArray(parsed.sections) ? parsed.sections : []
  for (const s of sections) {
    lines.push(`--------------------------------------------------------`)
    lines.push(`Section ${s.sectionCode}: ${s.sectionName}`)
    lines.push(`--------------------------------------------------------`)
    for (const q of s.questions ?? []) {
      lines.push(`[${q.questionCode}] ${q.questionText}`)
      if (q.unit) lines.push(`    Unit: ${q.unit}`)
      lines.push(`    Mapping: ${q.mappingSource ?? '—'}`)
      lines.push(`    Value:   ${formatVal(q.resolvedValue)} ${q.resolvedUnit ?? ''}`.trimEnd())
      lines.push(`    Status:  ${q.status}`)
      if (q.derivation) lines.push(`    Note:    ${q.derivation}`)
      if (q.sourceRecordIds?.length) {
        lines.push(`    Sources: ${q.sourceRecordIds.length} × ${q.sourceRecordType ?? 'record'}`)
      }
      lines.push('')
    }
  }
  if (parsed.trace?.note) {
    lines.push('---')
    lines.push(parsed.trace.note)
  }
  return lines.join('\n')
}

function formatVal(v: unknown): string {
  if (v === null || v === undefined) return '(no value)'
  if (typeof v === 'number') return String(v)
  return String(v)
}

// Convert a nested JSON report into a flat CSV. Strategy:
// - If top-level has `totals`, emit a totals section + flatten key records.
// - If top-level is array, emit column headers from the first element.
function jsonToCsv(obj: any): string {
  const rows: string[][] = []
  // Header for summary totals
  if (obj && typeof obj === 'object' && !Array.isArray(obj)) {
    // Pick a known flat array of records (byProject / logs / items) if available.
    const arrayKeys = Object.keys(obj).filter(k => Array.isArray(obj[k]))
    if (arrayKeys.length > 0) {
      // totals section
      if (obj.totals && typeof obj.totals === 'object') {
        rows.push(['# Section:', 'totals'])
        rows.push(['Key', 'Value'])
        for (const [k, v] of Object.entries(obj.totals)) rows.push([k, String(v ?? '')])
        rows.push([])
      }
      // First array of records → main CSV body
      const arr = obj[arrayKeys[0]]
      if (Array.isArray(arr) && arr.length > 0 && typeof arr[0] === 'object') {
        const headers = collectHeaders(arr)
        rows.push([`# Records: ${arrayKeys[0]}`])
        rows.push(headers)
        for (const item of arr) {
          rows.push(headers.map(h => csvCell(getPath(item, h))))
        }
        rows.push([])
      }
      // Sub-modules (ESG_SUMMARY case)
      if (obj.modules && typeof obj.modules === 'object') {
        rows.push(['# Modules:'])
        for (const [modName, mod] of Object.entries(obj.modules)) {
          if (mod && typeof mod === 'object' && (mod as any).totals) {
            rows.push([`## ${modName}`, 'totals'])
            for (const [k, v] of Object.entries((mod as any).totals)) rows.push([k, String(v ?? '')])
            rows.push([])
          }
        }
      }
    } else if (obj.totals) {
      rows.push(['Key', 'Value'])
      for (const [k, v] of Object.entries(obj.totals)) rows.push([k, String(v ?? '')])
    }
  } else if (Array.isArray(obj)) {
    if (obj.length > 0 && typeof obj[0] === 'object') {
      const headers = collectHeaders(obj)
      rows.push(headers)
      for (const item of obj) rows.push(headers.map(h => csvCell(getPath(item, h))))
    } else {
      rows.push(['value'])
      for (const v of obj) rows.push([String(v)])
    }
  } else {
    rows.push(['value'])
    rows.push([String(obj ?? '')])
  }
  return rows.map(r => r.map(csvCell).join(',')).join('\n')
}

function collectHeaders(arr: any[]): string[] {
  const set = new Set<string>()
  for (const item of arr) {
    if (item && typeof item === 'object') {
      for (const k of Object.keys(item)) set.add(k)
    }
  }
  return Array.from(set)
}
function getPath(obj: any, key: string): unknown {
  if (obj && typeof obj === 'object' && key in obj) return obj[key]
  return ''
}
function csvCell(v: unknown): string {
  if (v === null || v === undefined) return ''
  const s = typeof v === 'object' ? JSON.stringify(v) : String(v)
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`
  return s
}
